# Generated by Django 5.1.3 on 2024-12-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('cusine', models.TextField(max_length=100)),
                ('cusine_detail', models.TextField(max_length=500)),
                ('cusine_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=3)),
            ],
        ),
    ]
