# Generated by Django 5.1.3 on 2024-12-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_food_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('drink', models.TextField(max_length=100)),
                ('drink_detail', models.TextField(max_length=500)),
                ('price', models.IntegerField(default=True)),
                ('drink_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=3)),
            ],
        ),
    ]
