# Generated by Django 5.1.3 on 2024-12-28 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_dessert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='cusine_size',
        ),
    ]
