# Generated by Django 5.1.3 on 2024-12-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0005_remove_food_cusine_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('detail', models.TextField(max_length=500)),
                ('price', models.FloatField(default=True)),
            ],
        ),
    ]
