# Generated by Django 5.1.3 on 2025-01-03 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0008_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='submitted_at',
            new_name='created_at',
        ),
    ]
