# Generated by Django 5.1.3 on 2025-01-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0009_rename_submitted_at_order_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
