# Generated by Django 5.1.3 on 2025-01-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0010_rename_submitted_at_review_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='price',
            field=models.FloatField(default=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.FloatField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
