# Generated by Django 5.1.3 on 2025-01-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0012_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.FloatField(default=True),
        ),
    ]
