# Generated by Django 5.1.3 on 2025-01-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0015_contact_alter_drink_drink_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
